challenges:
  - category: Welcome
    source: challenges/welcome.yaml
  - category: Web
    source: challenges/web.yaml
defaults:
  type: dynamic # standard|dynamic
dynamic:
  initial: 500
  minimum: 100
  decay: 60
pages:
  - title: None
    route: index
    format: html
    content: |
      <div class="row">
          <div class="col-md-6 offset-md-3">
              <img class="w-100 mx-auto d-block" style="max-width: 500px;padding: 50px;padding-top: 14vh;" src="{logo}" />
              <h3 class="text-center">
                  <p>A cool CTF platform from <a href="https://ctfd.io">ctfd.io</a></p>
                  <p>Follow us on social media:</p>
                  <a href="https://twitter.com/ctfdio"><i class="fab fa-twitter fa-2x" aria-hidden="true"></i></a>&nbsp;
                  <a href="https://facebook.com/ctfdio"><i class="fab fa-facebook fa-2x" aria-hidden="true"></i></a>&nbsp;
                  <a href="https://github.com/ctfd"><i class="fab fa-github fa-2x" aria-hidden="true"></i></a>
              </h3>
              <br>
              <h4 class="text-center">
                  <a href="admin">Click here</a> to login and setup your CTF
              </h4>
          </div>
      </div>
    draft: 0
    hidden: 0
    auth_required: 0
files:
  - name: logo
    source: static/logo.png
users:
  - name: admin
    password: password
    email: admin@example.com
    type: admin # admin|user

